# Default values for example-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: datawire/qotm
  tag: 1.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: qotm_mapping
      prefix: /qotm/
      service: qotm

resources:
  limits:
    cpu: "0.1"
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
