apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "example-app.name" . }}
    helm.sh/chart: {{ include "example-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-api
      protocol: TCP
      name: http-qotm
  selector:
    app.kubernetes.io/name: {{ include "example-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
