apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "a8r-oidc-auth-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "a8r-oidc-auth-service.name" . }}
    helm.sh/chart: {{ include "a8r-oidc-auth-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "a8r-oidc-auth-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "a8r-oidc-auth-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: OIDC_SCOPE
              value: "openid profile"
            - name: OIDC_PROVIDER
              value: {{ .Values.oidc.provider }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: OIDC_REDIRECT_URI
              value: {{ .Values.oidc.redirectUri }}
            - name: OIDC_SKIP_PATH
              value: {{ .Values.oidc.skipPath | join ":" }}
            - name: REDIS_ADDRESS
              value: {{ .Values.redis.address }}
            {{- if not (eq (len .Values.redis.password) 0) }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            {{- end }}
            - name: SESSION_SECRET
              value: {{ .Values.sessionSecret | quote }}
            {{- if .Values.enableBearerIdToken }}
            - name: ENABLE_BEARER_ID_TOKEN
              value: "true"
            {{- end }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: KUBE_API_URL
              value: {{ .Values.kubeApiUrl }}
            - name: KUBE_API_PATH
              value: {{ .Values.kubeApiPath | join ":" }}
            - name: KUBECTL_CONTEXT
              value: {{ .Values.kubectlContext }}
            - name: KUBECTL_PAGE_PATH
              value: {{ .Values.kubectlPagePath }}
            - name: DEBUG
              value: {{ .Values.debug | quote }}
            - name: DEBUG_HIDE_DATE
              value: "true"
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              initialDelaySeconds: 20
              periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              initialDelaySeconds: 20
              periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
