image:
  repository: bitnami/postgresql
  tag: 11.3.0
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 200Mi

replication:
  enabled: false

initdbScripts:
  keycloak.sql: |
    CREATE USER dbuser WITH PASSWORD 'dbpass';
    CREATE DATABASE keycloak WITH OWNER dbuser;

postgresqlPassword: postgres
