image:
  pullPolicy: IfNotPresent

postgresqlDataDir: /data

persistence:
  enabled: true
  existingClaim: postgresql-pvc
  mountPath: /data

securityContext:
  enabled: true
  fsGroup: 26
  runAsUser: 26

initdbScripts:
  keycloak.sql: |
    CREATE USER dbuser WITH PASSWORD 'dbpass';
    CREATE DATABASE keycloak WITH OWNER dbuser;

postgresqlPassword: postgres
