cluster:
  enabled: false
  slaveCount: 1

persistence:
  existingClaim: redis-pvc

master:
  persistence:
    enabled: true
    size: 100Mi

slave:
  persistence:
    enabled: false
    size: 100Mi

usePassword: false

# password: redis
