apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "ambassador-certs.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-certs.name" . }}
    helm.sh/chart: {{ include "ambassador-certs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ include "ambassador-certs.name" . }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.{{ required ".Values.domain is required" .Values.domain }}"
  dnsNames:
    - "{{ required ".Values.domain is required" .Values.domain }}"
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains:
          - "*.{{ required ".Values.domain is required" .Values.domain }}"
          - "{{ required ".Values.domain is required" .Values.domain }}"
