apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: {{ include "ambassador-certs.name" . }}
    helm.sh/chart: {{ include "ambassador-certs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    email: {{ required ".Values.acmeEmail is required" .Values.acmeEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
{{- with .Values.acme.providers }}
      providers:
{{ toYaml . | indent 8 }}
{{- end }}

