apiVersion: v1
kind: Secret
metadata:
  name: acme-api-key
  labels:
    app.kubernetes.io/name: {{ include "ambassador-certs.name" . }}
    helm.sh/chart: {{ include "ambassador-certs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  api-key: {{ required ".Values.acme.apiKey is required" .Values.acme.apiKey | b64enc | quote }}
