{{- $kubeApiServer := .Values.kubeApiServer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "a8r-oidc-auth-service-activation.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "a8r-oidc-auth-service-activation.name" . }}
    helm.sh/chart: {{ include "a8r-oidc-auth-service-activation.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      proto: http
      auth_service: {{ include "a8r-oidc-auth-service-activation.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
      allowed_authorization_headers:
      - "X-Auth-Userinfo"
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: oidc-mapping
      prefix: /oidc/
      rewrite: ""
      service: {{ include "a8r-oidc-auth-service-activation.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
      {{- if not (eq (len .Values.kubeApiServer) 0) }}
      {{- range $path := .Values.kubeApiPath }}
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: kube-api-mapping-{{ $path }}
      prefix: {{ $path }}
      rewrite: ""
      tls: true
      host_rewrite: kube-apiserver
      timeout_ms: 600000
      service: {{ $kubeApiServer }}
      {{- end }}
      {{- end }}
      {{- if not (eq (len .Values.kubectlPagePath) 0) }}
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: kubectl-assets-mapping
      prefix: {{ .Values.kubectlAssetsPath }}
      rewrite: /assets
      service: {{ include "a8r-oidc-auth-service-activation.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: kubectl-mapping
      prefix: {{ .Values.kubectlPagePath }}
      rewrite: /kubectl
      service: {{ include "a8r-oidc-auth-service-activation.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
      {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.service.selector.name }}
