apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.osd }}
  labels:
    app.kubernetes.io/name: {{ include "rook-ceph-cluster.name" . }}
    helm.sh/chart: {{ include "rook-ceph-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.mgr }}
  labels:
    app.kubernetes.io/name: {{ include "rook-ceph-cluster.name" . }}
    helm.sh/chart: {{ include "rook-ceph-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
