# Default values for a8r-oidc-auth-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

oidc:
  provider: https://example.com/auth/realms/example
  clientId: example-client
  redirectUri: https://example.com/oidc/callback
  skipPath:
    - /auth
    # - /ambassador/v0/diag

redis:
  address: redis-master.redis:6379
  password: ""

sessionSecret: a8r-auth-sess

# Enable sending "Authorization: Bearer <id-token>" to upstream services
enableBearerIdToken: true

clusterName: example-cluster
kubeApiUrl: https://example.com
kubeApiPath:
  - /api
  - /logs
  - /metrics
  - /swagger
  - /ui
  - /version
kubectlContext: example-cluster

# Set the URL path of the kubectl configuration page to enable it
# Otherwise, set to empty ""
kubectlPagePath: /kubectl

debug: "a8r-oidc-auth-service:info"

# NODE_ENV
# 'production' hides system internal messages such as stack traces
nodeEnv: development

postInstall:
  sleepSeconds: 20

replicaCount: 1

image:
  repository: yatsu/a8r-oidc-auth-service
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
