apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql-pvc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgresql-pvc.name" . }}
    helm.sh/chart: {{ include "postgresql-pvc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.storage }}
