# Default values for a8r-oidc-auth-service-activation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: example.com

# Set the location of kube-apiserver to expose it public as /api/.
# Otherwise, set to empty ""
kubeApiServer: kubernetes.default:443

kubeApiPath:
  - /api
  - /logs
  - /metrics
  - /swagger
  - /ui
  - /version

# Set the URL path of the kubectl configuration page to enable it
# Otherwise, set to empty ""
kubectlPagePath: /kubectl

kubectlAssetsPath: /kubectl/assets

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  selector:
    name: a8r-oidc-auth-service
